title: Abuuzair Ansari Website
description: This website is an endeavor from my side to make projects and experience to be displayed on a public platform
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
author:
  name: Abuuzair Ansari
  email: abuuzair.c@gmail.com
  url: abuuzair-a.github.io

baseurl: [The base url for this blog.]
paginate: 
owner: Abuuzair Ansari
year: 2024
